[project]
org-name="eclk"
version="0.2.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "mysql-connector-java"
    version = "5.1.40"
    path = "lib/mysql-connector-java-5.1.40.jar"
    groupId = "mysql"
    modules = ["dist_controller"]
