[b7a.websub.hub.auth]
enabled=true
scopes="scope1"

[b7a.users]

[b7a.users.tom]
password="1234"
scopes="scope1"

[b7a.users.mary]
password="xyz"
scopes="scope2"

[b7a.users.peter]
password="pqr"
scopes="scope1"
