name: Platformer Generated resultdist Build
'on':
  push:
    branches:
      - ''
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/eclk/results-dist
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_958EB0E3_AE52_475C_983E_0341AB80734C }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file /distributor/Dockerfile /distributor/
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_FDDE02DC_14BC_4038_B428_48C2762EE344}}
          project-id: ${{secrets.PROJECT_ID_FDDE02DC_14BC_4038_B428_48C2762EE344}}
          token: ${{secrets.AUTOGENERATED_CICD_FDDE02DC_14BC_4038_B428_48C2762EE344}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 2b2533eb-6466-4790-a322-b1e7535e14ba
